### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by repeatedly** [treasure-data/omnibus-td-agent#101]
Check list:
- How to override environment variable: https://github.com/treasure-data/omnibus-td-agent/blob/77f2ae9ed2b51d99ccd9f5b47a52159f94b8a101/templates/etc/init.d/rpm/td-agent#L15
- How to set ulimit parameter: https://github.com/treasure-data/omnibus-td-agent/blob/77f2ae9ed2b51d99ccd9f5b47a52159f94b8a101/templates/etc/init.d/rpm/td-agent#L190
- How to export LD_PRELOAD: https://github.com/treasure-data/omnibus-td-agent/blob/77f2ae9ed2b51d99ccd9f5b47a52159f94b8a101/templates/etc/init.d/rpm/td-agent#L166

One fluentd example: https://gist.github.com/saidie/591157d2c9e306ff43d4

**Comment by repeatedly** [comment]
`EnvironmentFile` seems for 1st case.

**Comment by repeatedly** [comment]
`/etc/systemd/system/td-agent.service.d/limits.conf` seems to resolve 2nd case.

**Comment by repeatedly** [comment]
Environment is used for 3rd case.

```
Environment=LD_PRELOAD="${TD_AGENT_HOME}/embedded/lib/libjemalloc.so"
```

**Comment by cosmok** [comment]
Is there an update on this?

**Comment by repeatedly** [comment]
Here is an example of service file. Does anyone review this?

```
[Unit]
Description=Treasure Agent: A data collector for Treasure Data
Documentation=https://docs.treasuredata.com/articles/td-agent
After=network-online.target
Wants=network-online.target

[Service]
User=td-agent
Group=td-agent
LimitNOFILE=65536
Environment=LD_PRELOAD=/opt/td-agent/embedded/lib/libjemalloc.so
Environment=GEM_HOME=/opt/td-agent/embedded/lib/ruby/gems/2.4.0/
Environment=GEM_PATH=/opt/td-agent/embedded/lib/ruby/gems/2.4.0/
Environment=FLUENT_CONF=/etc/td-agent/td-agent.conf
Environment=FLUENT_PLUGIN=/etc/td-agent/plugin
Environment=FLUENT_SOCKET=/var/run/td-agent/td-agent.sock
PIDFile=/var/run/td-agent/td-agent.pid
Type=forking
ExecStart=/opt/td-agent/embedded/bin/fluentd --log /var/log/td-agent/td-agent.log --daemon /var/run/td-agent/td-agent.pid
ExecStop=/bin/kill -TERM ${MAINPID}
ExecReload=/bin/kill -HUP ${MAINPID}
Restart=always
TimeoutStopSec=120

[Install]
WantedBy=multi-user.target
```
