### ISSUE TITLE
td-agent installation fails

### ISSUE THREAD

**Issue by usergoodvery** [treasure-data/omnibus-td-agent#106]
hi

I attempted to install td-agent  using: 
curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent2.sh | sh
on ubuntu Xenial. However, I get the following error:

------------------------------------------------------------------------------
Setting up td-agent (2.3.3-0) ...
Conffile /etc/td-agent/td-agent.conf has been modified. Remain untouched.
Job for td-agent.service failed because the control process exited with error code. See "systemctl status td-agent.service" and "journalctl -xe" for details.
invoke-rc.d: initscript td-agent, action "start" failed.
dpkg: error processing package td-agent (--configure):
subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
td-agent
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Sub-process /usr/bin/dpkg returned an error code (1)
------------------------------------------------------------------------------------

Output of 'systemctl status td-agent.service':

● td-agent.service - LSB: data collector for Treasure Data
Loaded: loaded (/etc/init.d/td-agent; bad; vendor preset: enabled)
Active: failed (Result: exit-code) since Sun 2016-12-04 17:11:43 AEDT; 2min 3
Docs: man:systemd-sysv-generator(8)
Process: 5574 ExecStart=/etc/init.d/td-agent start (code=exited, status=1/FAIL

Dec 04 17:11:43 db.ufsrv systemd[1]: Starting LSB: data collector for Treasure D
Dec 04 17:11:43 db.ufsrv td-agent[5574]: Starting td-agent: start-stop-daemon: u
Dec 04 17:11:43 db.ufsrv td-agent[5574]: * td-agent
Dec 04 17:11:43 db.ufsrv systemd[1]: td-agent.service: Control process exited, c
Dec 04 17:11:43 db.ufsrv systemd[1]: Failed to start LSB: data collector for Tre
Dec 04 17:11:43 db.ufsrv systemd[1]: td-agent.service: Unit entered failed state
Dec 04 17:11:43 db.ufsrv systemd[1]: td-agent.service: Failed with result 'exit-

Your help is appreciated.

reagrds

**Comment by repeatedly** [comment]
I tried td-agent installation on Xenial and there is no error:

```
$ curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent2.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   563  100   563    0     0    451      0  0:00:01  0:00:01 --:--:--   451
This script requires superuser access to install apt packages.
You will be prompted for your password by sudo.
[sudo] password for repeatedly: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   934  100   934    0     0   1631      0 --:--:-- --:--:-- --:--:--  1632
OK
Get:1 http://packages.treasuredata.com/2/ubuntu/xenial xenial InRelease [1,929 B]
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease                 
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                    
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                              
Get:5 http://packages.treasuredata.com/2/ubuntu/xenial xenial/contrib amd64 Packages [400 B]
Get:6 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]            
Fetched 309 kB in 1s (199 kB/s)    
Reading package lists... Done
W: http://packages.treasuredata.com/2/ubuntu/xenial/dists/xenial/InRelease: Signature by key C901622B5EC4AF820C38AB861093DB45A12E206F uses weak digest algorithm (SHA1)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  td-agent
0 upgraded, 1 newly installed, 0 to remove and 93 not upgraded.
Need to get 67.2 MB of archives.
After this operation, 236 MB of additional disk space will be used.
Get:1 http://packages.treasuredata.com/2/ubuntu/xenial xenial/contrib amd64 td-agent amd64 2.3.3-0 [67.2 MB]
Fetched 67.2 MB in 55s (1,208 kB/s)                                                                                                              
Selecting previously unselected package td-agent.
(Reading database ... 86109 files and directories currently installed.)
Preparing to unpack .../td-agent_2.3.3-0_amd64.deb ...
Unpacking td-agent (2.3.3-0) ...
Setting up td-agent (2.3.3-0) ...
Adding system user `td-agent' (UID 110) ...
Adding new group `td-agent' (GID 118) ...
Adding new user `td-agent' (UID 110) with group `td-agent' ...
Not creating home directory `/home/td-agent'.
Installing default conffile /etc/td-agent/td-agent.conf ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
```

And systemctl is also no problem.

```
$ systemctl status td-agent.service
● td-agent.service - LSB: data collector for Treasure Data
   Loaded: loaded (/etc/init.d/td-agent; bad; vendor preset: enabled)
   Active: active (running) since Wed 2016-12-07 00:04:38 PST; 1min 43s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 50553 ExecStart=/etc/init.d/td-agent start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/td-agent.service
           ├─50577 /opt/td-agent/embedded/bin/ruby /usr/sbin/td-agent --log /var/log/td-agent/td-agent.log --daemon /var/run/td-agent/td-agent.pid
           └─50580 /opt/td-agent/embedded/bin/ruby /usr/sbin/td-agent --log /var/log/td-agent/td-agent.log --daemon /var/run/td-agent/td-agent.pid

Dec 07 00:04:37 ubuntu systemd[1]: Starting LSB: data collector for Treasure Data...
Dec 07 00:04:38 ubuntu td-agent[50553]: Starting td-agent:  * td-agent
Dec 07 00:04:38 ubuntu systemd[1]: Started LSB: data collector for Treasure Data.
```

I assume your environment has a problem.
Please check the differences between normal xenial and your setup first.

**Comment by usergoodvery** [comment]
Thanks. I suspect the installation works for countless individuals out there, otherwise you'd be hearing from others as well. 
It seems the package is installed, but fails to start, I checked syslog and also /var/log/td-agent (which is empty) but I cannot establish a lead as to why the startup script fails to kickoff td-agent. Is there anywhere that I can see more verbose output from the startup scrip?

**Comment by repeatedly** [comment]
Try: http://docs.fluentd.org/articles/trouble-shooting#check-uncaught-logs

**Comment by usergoodvery** [comment]
great thanks. I tried that and it complains of permissions problem as per the log below.
In my case though the entire /opt/td-agent folder tree is owned by user: td-agent group: td-agent.
What is the right folder permissions should look like?

drwxrwxr-x 2 td-agent td-agent 4096 Dec  4 12:59 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin



2016-12-08 20:14:20 +1100 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2016-12-08 20:14:20 +1100 [info]: starting fluentd-0.12.29
2016-12-08 20:14:20 +1100 [error]: unexpected error error="Permission denied @ dir_initialize - /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin"
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin.rb:87:in `open'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin.rb:87:in `entries'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin.rb:87:in `load_plugin_dir'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/plugin.rb:82:in `load_plugins'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/engine.rb:69:in `init'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:510:in `init_engine'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:158:in `block in start'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:366:in `call'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:366:in `main_process'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:339:in `block in supervise'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:338:in `fork'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:338:in `supervise'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:156:in `start'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/bin/fluentd:5:in `<top (required)>'
  2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
2016-12-08 20:14:20 +1100 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2016-12-08 20:14:20 +1100 [error]: /usr/sbin/td-agent:7:in `load'
  2016-12-08 20:14:20 +1100 [error]: /usr/sbin/td-agent:7:in `<main>'
2016-12-08 20:14:20 +1100 [info]: process finished code=256
2016-12-08 20:14:20 +1100 [warn]: process died within 1 second. exit.

**Comment by repeatedly** [comment]
I'm not sure but my result is below:

```
$ ls -al /opt
total 16
drwxr-xr-x  4 root root 4096 Aug  7 05:33 .
drwxr-xr-x 22 root root 4096 Dec  6 16:22 ..
drwxrwxr-x  7 root root 4096 Oct  3 20:55 td-agent
```

**Comment by usergoodvery** [comment]
I think I am about to give up on this... I tried changing the permissions back to root but the error still there.
There must be something else that is prodding this finicky thing... so much headache just to install an agent written in ruby

**Comment by repeatedly** [comment]
I heard this problem first and other users don't hit this problem.
So I assume your installation process has additinal step which causes this problem.

**Comment by repeatedly** [comment]
Close this issue because the problem doesn't seem to be related with td-agent package.
If the problem is package itself, someone reopen it.

**Comment by Ian-T-Price** [comment]
And yet it is the td-agent that fails to start... What else is needed to debug this issue?

pricei@dadmin-workstation:/$ uname -a
Linux dadmin-workstation.dsab-eud-999 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

----------------------

pricei@dadmin-workstation:/$ sudo systemctl status td-agent.service
● td-agent.service - LSB: data collector for Treasure Data
   Loaded: loaded (/etc/init.d/td-agent; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-01-03 11:28:03 GMT; 9s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9454 ExecStop=/etc/init.d/td-agent stop (code=exited, status=0/SUCCESS)
  Process: 18506 ExecStart=/etc/init.d/td-agent start (code=exited, status=1/FAILURE)

Jan 03 11:28:03 dadmin-workstation.dsab-eud-999 td-agent[18506]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
Jan 03 11:28:03 dadmin-workstation.dsab-eud-999 td-agent[18506]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:64:in `
Jan 03 11:28:03 dadmin-workstation.dsab-eud-999 td-agent[18506]:         from /opt/td-agent/embedded/bin/fluentd:22:in `<top (required)>'
Jan 03 11:28:03 dadmin-workstation.dsab-eud-999 td-agent[18506]:         from /usr/sbin/td-agent:7:in `load'
Jan 03 11:28:03 dadmin-workstation.dsab-eud-999 td-agent[18506]:         from /usr/sbin/td-agent:7:in `<main>'
Jan 03 11:28:03 dadmin-workstation.dsab-eud-999 systemd[1]: td-agent.service: Control process exited, code=exited status=1
Jan 03 11:28:03 dadmin-workstation.dsab-eud-999 td-agent[18506]:  * td-agent
Jan 03 11:28:03 dadmin-workstation.dsab-eud-999 systemd[1]: Failed to start LSB: data collector for Treasure Data.
Jan 03 11:28:03 dadmin-workstation.dsab-eud-999 systemd[1]: td-agent.service: Unit entered failed state.
Jan 03 11:28:03 dadmin-workstation.dsab-eud-999 systemd[1]: td-agent.service: Failed with result 'exit-code'.

**Comment by Odida** [comment]
Had the same issue but mine started working when I set /var/log/td-agent to 777. I think there is better permissions you can work from that if that was your case.

> chmod -R 777 /var/log/td-agent/

Env: Xenial, td-agent version 2.3.5

**Comment by RatiRanjanDas** [comment]
td-agent/0*         error     idle                10.222.0.41                         hook failed: "install"

I am getting this issue in juju status

**Comment by RatiRanjanDas** [comment]
td-agent/0*         error     idle                10.222.0.41                         hook failed: "install"

I am installing td-agent via charm but no luck. Getting error for td-agent in juju status with hook failed: "install". Please look into this 

td-agent/0*         error     idle            10.222.0.41                         hook failed: "install"
