### ISSUE TITLE
Debian package for stretch/sid

### ISSUE THREAD

**Issue by sabueso** [treasure-data/omnibus-td-agent#107]
Hi! 
Would be great to dispose of a Strech/Sid package installer.
Can be evaluated and if proceed, included in the roadmap?

Thanks!

**Comment by repeatedly** [comment]
No roadmap for now.
We provide td-agent for stable distributions, so we don't have a plan to provide packages to unstable / testing distributions.

**Comment by brycied00d** [comment]
Debian Stretch has been stable since [its release](https://www.debian.org/News/2017/20170617) 4 months ago. Any update on a release for Debian stable/stretch?

**Comment by joeweoj** [comment]
+1

**Comment by repeatedly** [comment]
Added td-agent 2.3.6 package to Debian 9.

https://docs.fluentd.org/v0.12/articles/install-by-deb#step-1-:-install-from-apt-repository

**Comment by sabueso** [comment]
@repeatedly thanks for you work!
