### ISSUE TITLE
Unable to build Deb package

### ISSUE THREAD

**Issue by IainColledge** [treasure-data/omnibus-td-agent#113]
Am building under Teamcity using the openjdk:8 base image with Ruby 2.1.8 and following the steps outlined.

The build fails with:

.rvm/gems/ruby-2.1.8@tdagent/bundler/gems/omnibus-software-d55178fb6d2a/config/software/openssl.rb:26:in `evaluate': undefined method `fips_mode?' for #<Omnibus::Software (Cleanroom)> (NoMethodError)

Any thoughts please?

**Comment by repeatedly** [comment]
Latest omnibus-software needs master branch of omnibus.
Update Gemfile and update omnibus gem should work.

Here is example to use omnibus's master branch: https://github.com/treasure-data/omnibus-td-agent/blob/4a18a74037f3c5b4ad6cb292cf903e68542d58f3/Gemfile#L8

**Comment by IainColledge** [comment]
Thanks, however I build from fresh sources every time, my Gemfile is the one you linked.

**Comment by repeatedly** [comment]
Current Gemfile always uses omnibus 5.5, not master: https://github.com/treasure-data/omnibus-td-agent/blob/4a18a74037f3c5b4ad6cb292cf903e68542d58f3/Gemfile#L7

**Comment by IainColledge** [comment]
Thanks very much, I can confirm that changing 

`gem 'omnibus', '5.5'`

to 

`gem 'omnibus', :github => 'chef/omnibus'`

results in a successful build.

**Comment by IainColledge** [comment]
Gemfile pull request accepted, thanks very much for your help in resolving this.
