### ISSUE TITLE
logrotate script error

### ISSUE THREAD

**Issue by azhestov** [treasure-data/omnibus-td-agent#119]
Hi, in your logrotate script(for ubuntu, i'm not check other OS) exist error in postrotate section.
If package installed, but not started, pid file not exist, test command return 1 and
every logrotate send to cron mail spam like this:

```
/etc/cron.daily/logrotate:
error: error running shared postrotate script for '/var/log/td-agent/td-agent.log '
run-parts: /etc/cron.daily/logrotate exited with return code 1
```

Good way to fix it:
/etc/logrotate.d/td-agent
```
@@ -8,6 +8,9 @@ 
  sharedscripts 
  postrotate 
    pid=/var/run/td-agent/td-agent.pid 
-    test -s $pid && kill -USR1 "$(cat $pid)" 
+    if [ -s "$pid" ] 
+    then 
+      kill -USR1 "$(cat $pid)" 
+    fi 
  endscript 
}
```

**Comment by repeatedly** [comment]
Thanks! I will apply this change later

**Comment by repeatedly** [comment]
master applied your patch. Thanks!
