### ISSUE TITLE
Issues installing fluent-plugin-bigquery on ubuntu

### ISSUE THREAD

**Issue by kpmbro** [treasure-data/omnibus-td-agent#121]
Hi , 

I am running on 
 $lsb_release -a 
`    
     Distributor ID:	Ubuntu
     Description:	Ubuntu 14.04.3 LTS
     Release:	14.04
     Codename:	trusty
`
and i have installed td-agent - using `apt-get  install td-agent`
i am trying to install fluent-plugin-bigquery using 
`gem install fluent-plugin-bigquery -v 0.2.15`
at first i got an error for having ruby<=2 so i have installed ruby2.2 ( i have add brightbox as a repo)
now i am getting the following error:

    Building native extensions.  This could take a while...
    ERROR:  Error installing fluent-plugin-bigquery:
    ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -r ./siteconf20170401-14625-1htq54f.rb extconf.rb
    mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

    extconf failed, exit code 1

    Gem files will remain installed in /var/lib/gems/2.2.0/gems/strptime-0.1.9 for inspection.
    Results logged to /var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/strptime-    0.1.9/gem_make.out`

at the plugin directory in /etc/td-agent/plugin/  i don't see any plugin installed .
i am new to ruby and i don't realy understand what is the problem , is there any stable way to use this plugin ? 
Thanks

**Comment by repeatedly** [comment]
See: http://docs.fluentd.org/v0.12/articles/plugin-management#gem-and-native-extension
