### ISSUE TITLE
Old td-agent deb packages get removed after update

### ISSUE THREAD

**Issue by raags** [treasure-data/omnibus-td-agent#127]
When a new td-agent package is pushed in the repo, the old package gets overridden, and becomes unavailable. The deb still exists, but the metadata gets updated to point to the package. This breaks workflows that still depend on the old package (especially in the cloud). Can we keep the old versions in place? APT already handles version upgrades.

Metadata updated : https://td-agent-package-browser.herokuapp.com/2/ubuntu/trusty/dists/trusty/contrib/binary-amd64

Old debs are still available : https://td-agent-package-browser.herokuapp.com/2/ubuntu/trusty/pool/contrib/t/td-agent

If s3repo is being used, there is an option --keep-old to not override and remove the old package metadata.

**Comment by repeatedly** [comment]
See: https://github.com/treasure-data/omnibus-td-agent/issues/66
