### ISSUE TITLE
td-agent2: Update bundled ruby to ruby 2.4

### ISSUE THREAD

**Issue by repeatedly** [treasure-data/omnibus-td-agent#139]
td-agent 2 uses ruby 2.1 and it is now unmtaintained by the community.
ruby 2.4 is latest stable and several gems start to remove ruby 2.1 from supported versions.
So updating bundled ruby is better.

NOTE: td-agent 3 uses ruby 2.4

The problem is ruby 2.1 and ruby 2.4 has difference library path.
So if there are installed gems, slient update may cause missing gem at startup.

To avoid the problem, separate repository path like td-agent 3 is one approach. If users want to use new td-agent 2, change repository path. Provide two td-agent versions together, e.g. 2.3.x and 2.5.x?
Or other approach?

What do you think?

**Comment by toru-takahashi** [comment]
The current version is 2.3.x. So, I think td-agent 2.4.x would be better.
https://docs.treasuredata.com/articles/td-agent-changelog#td-agent2-current-stable

But, as our doc, a user updates td-agent by the following way.
`apt-get update && apt-get install td-agent`

Ref. https://docs.treasuredata.com/articles/td-agent-upgrade#upgrade

But, I don't know whether we can protect a user to update td-agent to v2.4.x by the above command as default.
If `apt-get update && apt-get install td-agent` force to update to v2.4.x, I think we should do another plan.

**Comment by repeatedly** [comment]
> But, I don't know whether we can protect a user to update td-agent to v2.4.x by the above command as default.

Separate repository path protect this because users need to change their td-agent repository path before update.
ruby 2.1 based td-agent 2 is also provided in existing td-agent 2 repository.

**Comment by repeatedly** [comment]
td-agent 2.5 include ruby 2.5 so closed.
