### ISSUE TITLE
When is td-agent v3.0.2 planned?

### ISSUE THREAD

**Issue by nraddy** [treasure-data/omnibus-td-agent#142]
We are using some features from fleuntd version 0.14.19 and I saw that version3 of td-agent is updated to use fluentd v0.14.20. I am curious to know if (and when) there is going to be a release planned for v3.0.2 anytime soon? I am only looking for tentative timeline like this month, next month or end of the year. This would help us to plan whether to hack our system to update fluentd through gem after installing td-agent v3.0.1 or wait for the official release.

**Comment by repeatedly** [comment]
We are waiting ruby 2.4.2 release and ruby team has just released.
We will release td-agent 3.0.2 in this month after td-agent 2.3.6 release.
