### ISSUE TITLE
td-agent-gem broken in 2.3.6 release

### ISSUE THREAD

**Issue by diclophis** [treasure-data/omnibus-td-agent#149]
Hello,

I am running into issues related to `td-agent-gem` installation of pugins... see below:

```
$ sudo td-agent-gem
/usr/sbin/td-agent-gem: 4: /usr/sbin/td-agent-gem: /opt/td-agent/embedded/bin/fluent-gem: not found
```

**Comment by diclophis** [comment]
@repeatedly any chance you could take a look at this issue... this is a huge blocker in our organization

Also, please let me know if you need any more details

**Comment by repeatedly** [comment]
I'm not sure because I can't reproduce it.

```
# on ubuntu 14.04
$ curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh | sh
$ sudo /usr/sbin/td-agent-gem install fluent-plugin-route -v 0.2.0 --no-document
Fetching: fluent-plugin-route-0.2.0.gem (100%)
Successfully installed fluent-plugin-route-0.2.0
1 gem installed
```

So td-agent 2.3.6 has `/opt/td-agent/embedded/bin/fluent-gem` correctly.
You need to check why `/opt/td-agent/embedded/bin/fluent-gem` is removed from td-agent installation directory.

**Comment by diclophis** [comment]
I think i have a hunch what we might be doing wrong... we have some automation around `/usr/sbin/td-agent-gem uninstall -a --force fluentd` ... which i feel like is probably _not great (tm)_

I can't recall the specific issue we ran into before that prompted us to add this call to our configuration management system... but i am gonna see if i can not do that and get everything on our side working

**Comment by repeatedly** [comment]
> `/usr/sbin/td-agent-gem uninstall -a --force fluent`

Removing fluentd removes its related commands, e.g. `fluentd`, `fluent-gem`, `fluent-cat`.
So calling above command is very dangerous.

**Comment by diclophis** [comment]
Ok, we can close this, we are pretty sure that was our issue.
