### ISSUE TITLE
support for changing the name of the daemon

### ISSUE THREAD

**Issue by mr-salty** [treasure-data/omnibus-td-agent#15]
We discussed this topic with Kiyoto earlier in the week; I would like to investigate whether it's possible to support changing the name of the daemon more directly.

Our current approach is to fork this repo (https://github.com/GoogleCloudPlatform/google-fluentd), and manually replace 'td-agent' with 'google-fluentd' both in file contents and file names.  Merging upstream changes always leads to a lot of conflicts; resolving them is labor-intensive and error-prone.

Ideally the name of the daemon could be specified once (either in a file or on the command line when building) and the scripts would take care of all the string/filename substitutions during packaging.

**Comment by mr-salty** [comment]
I now have google-fluentd updated to use this and just wanted to say "thanks" to @tagomoris and you - it really is so much easier and cleaner this way.

**Comment by tagomoris** [comment]
It's pleasure for me :)
