### ISSUE TITLE
Error in td-agent startup when using systemd td-agent unit file

### ISSUE THREAD

**Issue by jernyreverb** [treasure-data/omnibus-td-agent#155]
**OS**: ubuntu 16.04 (xenial)
**Version**: td-agent 3.1.0

The systemd unit file added for td-agent 3.1.0 will take precedence over the init.d script.  The td-agent startup will fail because the `/var/run/td-agent` directory is missing.  The init.d script would create this on startup prior to this addition.

There is an option in systemd to do this as well it is `RuntimeDirectory`.  I believe the systemd unit file needs to include a `RuntimeDirectory=td-agent` entry to fix this.

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=

**Comment by repeatedly** [comment]
Thanks for the pointing this out.
I did test on Ubuntu/CentOS with this systemd file and it worked on my environment.
I'm not sure why but your point seems correct. I will add it soon.

**Comment by repeatedly** [comment]
BTW, how to install td-agent 3?
I did test again and it created `/var/run/td-agent`.

```
$ curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent3.sh | sh
[...]
Intallation completed. Happy Logging!

NOTE: In case you need any of these:
  1) security tested binary with a clear life cycle management
  2) advanced monitoring and management
  3) support SLA
Please check Fluentd Enterprise (https://fluentd.treasuredata.com/).
repeatedly@ubuntu:~$ ls /var/run
agetty.reload  crond.reboot	   do-not-hibernate  irqbalance.pid  motd.dynamic  resolvconf	 sendsigs.omit.d  sshd.pid  td-agent	user
blkid	       dbus		   initctl	     lock	     mount	   rsyslogd.pid  shm		  sudo	    tmpfiles.d	utmp
crond.pid      dhclient.ens33.pid  initramfs	     log	     network	   screen	 sshd		  systemd   udev	uuidd
```

I will add `RuntimeDirectory=td-agent` for safety but I want to know when this problem happens.

**Comment by jernyreverb** [comment]
I am not a 100% positive, but I have an older node that doesn't have this issue only because the td-agent unit file in `lib/systemd/system`.  My work around was to simply remove this file for now and let systemd use the `init.d` script.

Thanks so much for your feedback and all your work.

**Comment by jernyreverb** [comment]
My use case is that it shows up after boot from a pre-baked ami.  I use the `td-agent` cookbook to setup td-agent and I create an AWS ami from the cookbook.

I then boot the AMI as an EC2 instance and at bootup that directory will not exist and you will get the error.

**Comment by repeatedly** [comment]
> I then boot the AMI as an EC2 instance and at bootup that directory will not exist and you will get the error.

I see. Thanks for the information.

**Comment by sandstrom** [comment]
I think the correct solution is to add this file:

**/usr/lib/tmpfiles.d/td-agent.conf**

```sh
d /var/run/td-agent 0755 td-agent td-agent - -
```

That way, the `td-agent` dir in `/var/run` will be recreated on system bootup.

See this SO-question for more details: https://askubuntu.com/a/306479

**Comment by repeatedly** [comment]
Thanks. I first knew this approach :)

**Comment by wallywest** [comment]
Nice!  I wasn't sure the preferred approach with systemd.  If this is the recommended method all the better.  Thanks again!
