### ISSUE TITLE
Failed to install fluent-plugin-amqp

### ISSUE THREAD

**Issue by rs1986x** [treasure-data/omnibus-td-agent#162]
I tried to track the dependencies but i think there must be something wrong with the version. I am not ruby expert, thank you very much for the support
```
td-agent-gem install fluent-plugin-amqp
Fetching: amq-protocol-2.3.0.gem (100%)
ERROR:  Error installing fluent-plugin-amqp:
ruby --version
ruby 2.2.8p477 (2017-09-14 revision 59906) [x86_64-linux-gnu]
```

**Comment by rs1986x** [comment]
`/opt/td-agent/embedded/bin# td-agent-gem install fluent-plugin-amqp --debug
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /opt/td-agent/embedded/lib/ruby/2.1.0/resolv.rb:169 - LoadError
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /opt/td-agent/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `Resolv::DNS::Config::NXDomain' at /opt/td-agent/embedded/lib/ruby/2.1.0/resolv.rb:547 - _rubygems._tcp.api.rubygems.org
Exception `Resolv::DNS::Config::NXDomain' at /opt/td-agent/embedded/lib/ruby/2.1.0/resolv.rb:547 - _rubygems._tcp.api.rubygems.org
Exception `Resolv::ResolvError' at /opt/td-agent/embedded/lib/ruby/2.1.0/resolv.rb:492 - DNS result has no information for _rubygems._tcp.api.rubygems.org
Exception `Errno::EEXIST' at /opt/td-agent/embedded/lib/ruby/2.1.0/fileutils.rb:250 - File exists @ dir_s_mkdir - /opt/td-agent/embedded/lib/ruby/gems/2.1.0
Exception `Gem::InstallError' at /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/installer.rb:611 - amq-protocol requires Ruby version >= 2.2.
ERROR:  Error installing fluent-plugin-amqp:
        amq-protocol requires Ruby version >= 2.2.`

`/opt/td-agent/embedded/bin# ./ruby --version
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]`

**Comment by repeatedly** [comment]
Error said your dependent library requires ruby 2.2 but td-agent's ruby is 2.1.

**Comment by repeatedly** [comment]
td-agent 2.5 or 3 resolves this issue.
