### ISSUE TITLE
Can you add installation script for Debian?

### ISSUE THREAD

**Issue by okkez** [treasure-data/omnibus-td-agent#167]
[Installing Fluentd Using deb Package](https://docs.fluentd.org/v1.0/articles/install-by-deb) does not describe installation for Debian (jessie and stretch). It describes only Ubuntu.

So I wrote shell script based on Ubuntu version.
https://gist.github.com/okkez/831ab852528d52eabad0684c938db17b

But this script uses `lsb_release -sc`. lsb-release package depends on some packages.
So we can also code name instead of `lsb_release -sc`.

**Comment by repeatedly** [comment]
Added

**Comment by okkez** [comment]
Thanks!!
