### ISSUE TITLE
Ubuntu 18.04 Bionic package

### ISSUE THREAD

**Issue by arunderwood** [treasure-data/omnibus-td-agent#175]
Are there plans or a roadmap for adding an Ubuntu 18.04 package?

**Comment by repeatedly** [comment]
We don't have exact date for it.
Maybe, june or later.

**Comment by sandstrom** [comment]
@repeatedly support for 18.04 would be awesome! 🏅

**Comment by sandstrom** [comment]
@repeatedly friendly ping 😄 

*(I checked your [install page](https://docs.fluentd.org/v1.0/articles/install-by-deb) and couldn't find anything for Bionic)*

**Comment by sandstrom** [comment]
This is fixed now, bionic package is released, this issue can be closed.

Thanks @repeatedly! 🥇

**Comment by mandyjohar23** [comment]
@repeatedly Is there plan to add support for `td-agent 2.3 or earlier` for bionic ? Current installation guide only refers to td-agent 2.5 or above refs https://docs.fluentd.org/v0.12/articles/install-by-deb

**Comment by repeatedly** [comment]
@mandyjohar23 No plan. td-agent 2.3 uses outdated ruby 2.1 and it has security concern.
