### ISSUE TITLE
td-agent 3.2.0 for Windows

### ISSUE THREAD

**Issue by Techcadia** [treasure-data/omnibus-td-agent#180]
https://github.com/treasure-data/omnibus-td-agent/pull/173

This PR merged it into master but the release was never cut for windows.

I asked twice on the PR but I figure its time for a new issue.

The latest version listed is 3.1.1-0
https://td-agent-package-browser.herokuapp.com/3/windows

Thanks

**Comment by Techcadia** [comment]
Bump

**Comment by grjones** [comment]
Bump please :)

**Comment by repeatedly** [comment]
Sorry for the late response.
We have just released td-agent 3.2.1: https://td-agent-package-browser.herokuapp.com/3/windows/
