### ISSUE TITLE
[Question] Why manual steps for Windows MSI?

### ISSUE THREAD

**Issue by grjones** [treasure-data/omnibus-td-agent#188]
I'm just curious.  There are a few manual steps for the Windows MSI, including registering the service and starting it as described here:
https://docs.fluentd.org/v1.0/articles/install-by-msi#step-3:-register-td-agent-to-windows-service

Is there a reason this couldn't just happen automatically in the MSI?  Why is it manual?

**Comment by repeatedly** [comment]
> Is there a reason this couldn't just happen automatically in the MSI? Why is it manual?

Because we are not expert of msi packaging.
If someone send a patch for it, we can review and accept it.

**Comment by grjones** [comment]
Ok. Just curious. Thanks!!
