### ISSUE TITLE
rpm package for td-agent3 /etc/sysconfig/td-agent vars not working

### ISSUE THREAD

**Issue by jordo1138** [treasure-data/omnibus-td-agent#198]
I'm not sure if I"m missing something but I can't get my env vars in right now from the /etc/sysconfig/td-agent file. It's been a while since I tried from td-agent vs docker which works and also been a while since doing it in redhat/centos where I know for debian it was sourced from /etc/default/td-agent 

any suggestions?
td-agent file
export TEAM="teamx"

```
<filter **>
  @ type record_transformer
  <record>
    team "#{ENV['TEAM']}"
  </record>
</filter>
```

**Comment by jordo1138** [comment]
Found the issue @repeatedly , so seems /etc/init.d/td-agent script still source like 
`# Read configuration variable file if it is present
if [ -f "${TD_AGENT_DEFAULT}" ]; then
  . "${TD_AGENT_DEFAULT}"
fi`

But in my case, I install on Redhat 7 and run using systemctl / systemd
So I check /usr/lib/systemd/system/td-agent.service and found many
Environment= lines but nothing to /etc/syconfig/td-agent
so I just add
`EnvironmentFile=/etc/sysconfig/td-agent`
then systemctl daemon-reload
now the vars are there and I found the format can't `"export VAR="var"` which was maybe old way if you do some google group search in fluentd/tdagent
need to just be file like 
`VAR="var"`  and the quotes just incase you have a space or something...

**Comment by repeatedly** [comment]
Hmm... when `EnvironmentFile` file is not exist, this directive doesn't raise error, right?
If so, we can add `EnvironmentFile=/etc/sysconfig/td-agent` in systemd unit file

**Comment by jordo1138** [comment]
@repeatedly unfortunately it does raise an error if the file isn't found, I tested by removing the file and leaving the directive

**Comment by repeatedly** [comment]
Ah, I see. No conditional way for `EnvironmentFile`, right?
If so, adding note to documentation is one way.

**Comment by jordo1138** [comment]
@repeatedly good news, you just gave me the idea to find the way around it...
so in /usr/lib/systemd/system/td-agent.service need to add it like this 
`EnvironmentFile=-/etc/sysconfig/td-agent`

the "-" after = makes it conditional, and starts without error now whether the file exists or not

**Comment by jordo1138** [comment]
PR#199 submitted. Let me know if you need a new test case for this, I can look into adding one, I only made the change needed in the template for systemd to source the vars

**Comment by jordo1138** [comment]
#199 merged, closing issue thanks
