### ISSUE TITLE
systemd unit file for debian/ubuntu refers to /etc/sysconfig/td-agent

### ISSUE THREAD

**Issue by rene00** [treasure-data/omnibus-td-agent#207]
The td-agent debian package ships a td-agent systemd unit file which refers to `/etc/sysconfig/td-agent` for `EnvironmentFile`:

https://github.com/treasure-data/omnibus-td-agent/blob/e1a5183960be1bae5caa76ae297da97fec2ac396/templates/etc/systemd/td-agent.service.erb#L18

The `/etc/sysconfig` directory does not exist on a pristine debian/ubuntu install. `/etc/default` is generally used instead.

From the [Debian Policy manual](https://www.debian.org/doc/debian-policy/ch-opersys.html#writing-the-scripts):

 > To ease the burden on the system administrator, such configurable values should not be placed directly in the script. Instead, they should be placed in a file in /etc/default, which typically will have the same base name as the init.d script. 

Is there a chance that the systemd unit file that ships with the debian package use`/etc/default/td-agent` instead of `/etc/sysconfig/td-agent`?

**Comment by repeatedly** [comment]
Fixed by https://github.com/treasure-data/omnibus-td-agent/pull/211
3.5.0 fixes this problem.
