### ISSUE TITLE
TD agent plugin install failed (td-agent-gem install fluent-plugin-elasticsearch)

### ISSUE THREAD

**Issue by nikhilraj474** [treasure-data/omnibus-td-agent#222]
Hi Please can any one help me out 

we were installing the plugin td-agent-gem install fluent-plugin-elasticsearch

```
 root@TEST03:~# systemctl stop td-agent.service
root@TEST03:~# td-agent-gem install fluent-plugin-elasticsearch

ERROR:  While executing gem ... (SocketError)
    getaddrinfo: Name or service not known
```

I have even checked the DNS entry was able to ping the DNS servers.

**Comment by repeatedly** [comment]
> getaddrinfo: Name or service not known

Your network environment seems to failed to resolve `www.rubygems.org`. `geaddrinfo` error is C/system level, so the problem is outside of td-agent. You need to resolve the problem on your side.

**Comment by nikhilraj474** [comment]
when I checked to resolve it's giving me the.

root@TEST03:~# host rubygems.org
rubygems.org has address 151.101.0.70
rubygems.org has address 151.101.128.70
rubygems.org has address 151.101.64.70
rubygems.org has address 151.101.192.70
rubygems.org has IPv6 address 2a04:4e42::70
rubygems.org mail is handled by 10 mxa.mailgun.org.
rubygems.org mail is handled by 10 mxb.mailgun.org.
