### ISSUE TITLE
Error: "This installation package could not be opened..." 3.6.0

### ISSUE THREAD

**Issue by flurreN** [treasure-data/omnibus-td-agent#236]
Trying to run the latest msi build but I get this error.
`Error: "This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer package."
`
I can install 3.5.1 without any problem.

OS: Windows 10 Enterprise Version 10.0.17763 build 17763
Also tried on a Windows Server 2019 Standard Version 10.0.17763 build 17763

**Comment by repeatedly** [comment]
I confirmed the problem and the problem is the size of msi, only 24mb...
I have just re-uploaded the msi package and this size is 30mb.
So this new msi should work.

**Comment by flurreN** [comment]
Thanks, it's working now. Closing this.
