### ISSUE TITLE
change ruby version?

### ISSUE THREAD

**Issue by eredi93** [treasure-data/omnibus-td-agent#237]
Is it possible to change the ruby version `td-agent` is using?

https://github.com/joker1007/fluent-plugin-arrow but i cannot use it because of the ruby version the agent is using.
https://github.com/joker1007/fluent-plugin-arrow/issues/2

basically the plugin relies on https://github.com/apache/arrow/tree/master/ruby/red-arrow which relies on the use of `alias_method` which was made public in `ruby 2.5`
is it possible to upgrade the td-agent ruby version? 
it seems to be defined https://github.com/treasure-data/omnibus-td-agent/blob/d2f46d1d1f24f34b92b13fd26c3883b3be63ca94/config/projects/td-agent3.rb#L22 
i guess https://github.com/treasure-data/omnibus-td-agent/issues/209 would fix my problem but i was wondering if there was a way for me to get unblocked and use the arrow plugin.

Thanks

**Comment by repeatedly** [comment]
td-agent 4 has been released.
