### ISSUE TITLE
Trying to execute ./configure on Windows 10

### ISSUE THREAD

**Issue by flurreN** [treasure-data/omnibus-td-agent#239]
Im using [this](https://github.com/treasure-data/omnibus-td-agent/blob/master/td-agent-on-windows.md) to build a .msi installer. I get this error and I cant find anything to solve it. Tried to change it from "./configure" to "configure" but didnt work. Cant even find the supposed configure file its trying to execute.
```
[Builder: libffi] I | 2020-03-03T03:00:26-08:00 | $ ./configure --build=x86_64-w64-mingw32 --prefix=C:/opt/td-agent/embedded --disable-multi-os-directory
        [Builder: libffi] I | 2020-03-03T03:00:26-08:00 | Execute: `./configure --build=x86_64-w64-mingw32 --prefix=C:/opt/td-agent/embedded --disable-multi-os-directory': 0.047s

...

    '.' is not recognized as an internal or external command,
operable program or batch file.
````

Did this on ruby 2.4 as 2.3.1 couldnt build omnious

**Comment by flurreN** [comment]
How are you building your .msi installer?

**Comment by repeatedly** [comment]
I use https://github.com/treasure-data/omnibus-td-agent/blob/master/td-agent-on-windows-with-chef.md

**Comment by flurreN** [comment]
> I use https://github.com/treasure-data/omnibus-td-agent/blob/master/td-agent-on-windows-with-chef.md

Thanks, which ruby version are you using?

**Comment by flurreN** [comment]
Still trying to get it to work, but are you still using chefdk 3.2.23? Just making sure as the guide hasnt been updated in a while. @repeatedly

**Comment by repeatedly** [comment]
> are you still using chefdk 3.2.23?

Yes but I uses windows 2012 R2 environment. I didn't test the build on Windows 10.

@cosmo0920 What the version do you use for build test?

**Comment by cosmo0920** [comment]
I used Windows 10 1909.

**Comment by flurreN** [comment]
> I used Windows 10 1909 and I didn't use chefdk.
> I used MSYS2 and Ruby 2.5.6 to build package.
> 
> I use this procedure: https://github.com/treasure-data/omnibus-td-agent/blob/master/td-agent-on-windows.md

@cosmo0920 Do you run everything in powershell/cmd and not bash?

**Comment by cosmo0920** [comment]
Yes. I built omnibus-td-agent with PowerShell Core 6 (which is almost equivalent to built-in PowerShell).

**Comment by flurreN** [comment]
@cosmo0920  hmm.. Still not working, tried with ruby 2.5.6 and Powershell Core 6. Still getting stuck on the ./configure error

**Comment by cosmo0920** [comment]
I use Ruby 2.5.6 and MSYS2 not Devkit.
I can work to prepare Windows docker building environment.

**Comment by flurreN** [comment]
> I use Ruby 2.5.6 and MSYS2 not Devkit.
> I can work to prepare Windows docker building environment.

That would be really great!

**Comment by flurreN** [comment]
`ridk exec` worked for me, thank you @cosmo0920 (not finished yet, but seemes to work)

I have some other questions:
When using the `ridk exec` it only wants to use c:\msys2 which is not the default path, no problem just rename and re-path, but is there a way to change that or how did you do it if you stumbled across the same problem

I also noticed when for example building and there was a missing path and you add it and rebuild it always get stuck on nokigiri with errors, so I had to do the `bin/omnibus clean td-agent3 --purge` is there anyway to just clean one of the building parts, tried to remove files here and there but nothing seemed to work... takes a lot of time to rebuild everything.

**Comment by cosmo0920** [comment]
> When using the `ridk exec` it only wants to use c:\msys2 which is not the default path, no problem just rename and re-path, but is there a way to change that or how did you do it if you stumbled across the same problem

I just created symlink for `C:\msys2` which links to `C:\msys64`(installation directory).



> I also noticed when for example building and there was a missing path and you add it and rebuild it always get stuck on nokigiri with errors, so I had to do the `bin/omnibus clean td-agent3 --purge` is there anyway to just clean one of the building parts, tried to remove files here and there but nothing seemed to work... takes a lot of time to rebuild everything.

I just purged staging directories entirely.
Yeah, this way consumes a lot of time.

**Comment by flurreN** [comment]
> > When using the `ridk exec` it only wants to use c:\msys2 which is not the default path, no problem just rename and re-path, but is there a way to change that or how did you do it if you stumbled across the same problem
> 
> I just created symlink for `C:\msys2` which links to `C:\msys64`(installation directory).
> 
> > I also noticed when for example building and there was a missing path and you add it and rebuild it always get stuck on nokigiri with errors, so I had to do the `bin/omnibus clean td-agent3 --purge` is there anyway to just clean one of the building parts, tried to remove files here and there but nothing seemed to work... takes a lot of time to rebuild everything.
> 
> I just purged staging directories entirely.
> Yeah, this way consumes a lot of time.

Thanks!

Another question while am at it, is it possible to include files in the msi installer, I know you can edit td-agent.conf but is it possible to like put in an extra file of something
