### ISSUE TITLE
[Bug] misleading docs.treasure.com in the project description

### ISSUE THREAD

**Issue by sachincool** [treasure-data/omnibus-td-agent#249]
![image](https://user-images.githubusercontent.com/25671488/79693499-a5614580-8288-11ea-86f3-029ffce23d0d.png) I think the domain is changed now?  The [link](https://docs.treasuredata.com/articles/td-agent-changelog) in the description is depreciated now. can we please update it 😄 I don't know the actual link, otherwise I would have sent a PR. Thanks

**Comment by repeatedly** [comment]
Thanks for the report. Just updated links.
