### ISSUE TITLE
td-agent-ui is not installed

### ISSUE THREAD

**Issue by ailisp** [treasure-data/omnibus-td-agent#250]
Following docs on fluentd. My os is ubuntu 18.04,
```
curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-bionic-td-agent3.sh | sh
```
tg-agent is installed and working, but there's no td-agent-ui

**Comment by repeatedly** [comment]
Yes. We removed td-agent-ui from td-agent because lots of people don't use it with td-agent package and it increase package size.

**Comment by ailisp** [comment]
Is there a way to install it on Debian/Ubuntu? I didn't see it in doc. Thanks!

**Comment by repeatedly** [comment]
See README: https://github.com/fluent/fluentd-ui#requirements
td-agent 3 uses ruby 2.4, so rails v5 or earlier is needed.

BTW, this is not td-agent issue. Closed.

**Comment by ailisp** [comment]
Thanks! I can install fluentd-ui, but it's still nice to see a separate td-agent-ui debian package that work out of box with td-agent since you used to have td-agent + td-agent-ui.
