### ISSUE TITLE
Missing td-agent 3.7.1 packages for debian

### ISSUE THREAD

**Issue by aeber** [treasure-data/omnibus-td-agent#252]
Thanks for releasing td-agent 3.7.1!

Although packages for Ubuntu / Redhat / Centos / Windows have been released to packages.treasuredata.org, the ones for Debian still seem to be missing.

Is this on purpose?

**Comment by repeatedly** [comment]
Ah, I forgot to upload debian packages. We will release it soon.

**Comment by repeatedly** [comment]
Just uploaded. Please check.

**Comment by aeber** [comment]
Yes, thank you!
