### ISSUE TITLE
Changelog links are dead

### ISSUE THREAD

**Issue by SuperQ** [treasure-data/omnibus-td-agent#258]
The README changelog link is dead.

It points to the old docs site, the links on the redirect page point to very old, out of date changelog.

The only [new docs site changelog](https://tddocs.atlassian.net/wiki/spaces/PD/pages/6291635/The+td-agent+ChangeLog) ends at 3.5.1.

Where can I find change information for newer packages of td-agent?

**Comment by repeatedly** [comment]
Our documentation team forgot to update td-agent changelog from zendesk.
I have created ticket for fixing this issue.

**Comment by SuperQ** [comment]
Maybe easier would be to keep the changelog in the repo. :smile_cat:

**Comment by Houlistonm** [comment]
> 
> 
> Maybe easier would be to keep the changelog in the repo. 😸

I would actually prefer this solution.
That way any forks of the repo (and PR's) can have and maintain the changelog.

**Comment by repeatedly** [comment]
td-agent 4 includes changelog in the repository: https://github.com/fluent-plugins-nursery/td-agent-builder/blob/master/CHANGELOG.md
Convert atlassian changelog to markdown has less merit because we are moving to td-agent 4. So keep td-agent 3 or older changelog on atlasiaan.

**Comment by SuperQ** [comment]
@repeatedly That's great! I don't see any breaking changes listed, is this officially released? I don't see it on `http://packages.treasuredata.com/`.
