### ISSUE TITLE
BUG: memory leak in td-agent 3.8.0

### ISSUE THREAD

**Issue by Houlistonm** [treasure-data/omnibus-td-agent#261]
We've been running td-agent 3.8.0 for the past week in our dev environment(s) (upgrade from 3.6.0).
The OOM Killer on our dev instances reaped the worker-0 (single worker) this past weekend when the kernel detected we were running out of memory.  

We average 15M log messages/day

Our installation is stock with the exception of the changes referenced in #260 

Memory usage from our Grafana dashboards displaying two days of data (the servers were restarted Sat AM).  
The sharp spikes are when our clamav was performing a scan.

CI ENV:
![image](https://user-images.githubusercontent.com/24305231/86607593-739e7780-bf77-11ea-90b9-08ae1182c670.png)

DEV ENV:
![image](https://user-images.githubusercontent.com/24305231/86607802-bbbd9a00-bf77-11ea-9cc1-54145cc1fbd5.png)

**Comment by Houlistonm** [comment]
Supporting information.

We were on 3.6.0 
On 6/23 then we upgraded to 3.7.1
On 6/30 we upgraded to 3.8.0 (and metrics stopped working).
![image](https://user-images.githubusercontent.com/24305231/86614278-be70bd00-bf80-11ea-94a8-f098315e683d.png)

**Comment by repeatedly** [comment]
Could you check this behavior happen with following two cases?

- latest fluentd and fluent-plugin-prometheus v1.7.3
- fluentd v1.9.2 / v1.10.0 and fluent-plugin-prometheus v1.8.1
