### ISSUE TITLE
Failed to start td-agent with aarch64

### ISSUE THREAD

**Issue by rluisr** [treasure-data/omnibus-td-agent#264]
Summary
========
Failed to start td-agent **4.0.0** on CentOS 8 and 7.

```
# cat /var/log/messages

Aug 13 18:18:00 ip-10-105-44-194 fluentd[15556]: <jemalloc>: Unsupported system page size
Aug 13 18:18:00 ip-10-105-44-194 fluentd[15556]: <jemalloc>: Unsupported system page size
Aug 13 18:18:00 ip-10-105-44-194 fluentd[15556]: [FATAL] failed to allocate memory
```

Reproduce
=========
```
# yum install http://packages.treasuredata.com.s3.amazonaws.com/4/redhat/8/aarch64/td-agent-4.0.0-1.el8.aarch64.rpm -y
# systemctl start td-agent
```

Environnment
===========
- CentOS Linux release 8.2.2004 (Core)
- aarch64
- AWS EC2 ARM instance (M6g)

**Comment by ashie** [comment]
Cloud you move the issue to https://github.com/fluent-plugins-nursery/td-agent-builder?
td-agent 4.0.0 is built by it instead of Omnibus.

**Comment by rluisr** [comment]
of cause. thank you for sharing url.

**Comment by ashie** [comment]
Thanks!
