### ISSUE TITLE
The newest td-gent (4.1.0-1) does not detect log rotation

### ISSUE THREAD

**Issue by S3ky** [treasure-data/omnibus-td-agent#280]
Hi,

after upgrade td-agent to the latest version 4.1.0 (Fluentd 1.12.1, CentOS 7) we found a bug, that Fluentd did not detect log rotation. We manually confirmed that it was working in the td-agent v.4.0.1.

(Steps to reproduce log rotation problem): 

We reproduced it by making an mv on the log file and then restarting our service, which is producing log files. After we restarted our service, the service started writing to another file. During this process, I checked the logs of the td-agent, that there was no message, and I looked in the pos file and it was clear that there was still inode from the file we moved.

Thank you for looking into this.

**Comment by ashie** [comment]
Could you please close this one (I don't have the permission to do it here)?
You post a same issue at https://github.com/fluent/fluentd/issues/3324 and we are aware both of them.
In addition, we migrated to [td-agent-builder](https://github.com/fluent-plugins-nursery/td-agent-builder) as of 4.0 and [we are preparing 4.1.1 to fix this issue](https://github.com/fluent-plugins-nursery/td-agent-builder/pull/288).
