### ISSUE TITLE
Custom plugin not detected when placed in /etc/td-agent/plugin

### ISSUE THREAD

**Issue by olegcarguy** [treasure-data/omnibus-td-agent#287]
(Hopefully I'm inputting this bug into the correct repo)

I'm trying to place this custom plugin file (https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/source/code/plugins/out_oms_api.rb) in my existing td-agent V4 installation on Ubuntu 18.04. When placing this file in /etc/td-agent/plugin, td-agent is not detecting this plugin exists. Here is the excerpt from my td-agent.conf file:

<match oms.api.ModSecurityLog>
  type out_oms_api
  log_level info
  buffer_chunk_limit 5m
  buffer_type file
  buffer_path /tmp/out_oms_api_modsecurity*.buffer
  buffer_queue_limit 10
  flush_interval 20s
  retry_limit 10
  retry_wait 30s
</match>
and here is the excerpt from td-agent.log

2021-09-18 11:06:56 -0500 [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Unknown output plugin 'out_oms_api'. Run 'gem search -rd fluent-plugin' to find plugins"

Am I doing something wrong?

**Comment by ashie** [comment]
omnibus-td-agent is obsolete, fluent-plugins-nursery/fluent-package-builder is the right place to file it.

https://github.com/fluent-plugins-nursery/fluent-package-builder/issues/334
