### ISSUE TITLE
#DEBHELPER# tags are not expanded during deb build process

### ISSUE THREAD

**Issue by mr-salty** [treasure-data/omnibus-td-agent#29]
The postinst/prerm/postrm scripts all have a '#DEBHELPER#' tag, i.e.:

https://github.com/treasure-data/omnibus-td-agent/blob/master/templates/package-scripts/td-agent/deb/postinst#L107

These are supposed to be replaced by actual code by debhelper/dh_installdeb but this is not happening, so the tag ends up in the deb package verbatim (see below for example).

This leads to some issues:
* In postinst, the generated code runs update-rc.d which is what makes the agent start at boot time (via links in /etc/rc*.d), but this is not happening, so td-agent will not automatically run if the machine reboots.
* It should also do 'invoke-rc.d ... start' in postinst and 'invoke-rc.d stop' in prerm, which would appear to be the root cause of the behavior I reported in #14 

```
$ curl -O 'http://packages.treasuredata.com.s3.amazonaws.com/2/debian/wheezy/pool/contrib/t/td-agent/td-agent_2.1.4-0_amd64.deb
$ dpkg-deb -R td-agent_2.1.4-0_amd64.deb .
$ tail DEBIAN/postinst 
if [ ! -e "/etc/default/td-agent" ]; then
  cat > /etc/default/td-agent <<EOF
# This file is sourced by /bin/sh from /etc/init.d/td-agent
# Options to pass to td-agent
DAEMON_ARGS=""

EOF
fi

#DEBHELPER#
```

**Comment by repeatedly** [comment]
Ah, I see.
I forgot omnibus doesn't use db_xxx helpers.

This problem seems to resolve by copying actual code from td-agent 1.

**Comment by repeatedly** [comment]
I sent a patch.
I will check #28 and #29 again.
