### ISSUE TITLE
Question Will ubuntu jammy packages be supported?

### ISSUE THREAD

**Issue by pyama86** [treasure-data/omnibus-td-agent#294]
I wasn't sure whether to report it here or contact you via the [contact form](https://www.treasuredata.com/contact-us/), but it seems that ubuntu jammy is not yet supported in the apt repository at this time. Are there any plans to support this?
https://td-agent-package-browser.herokuapp.com/4/ubuntu/

**Comment by ashie** [comment]
For td-agent 4 or later, the project page is moved to https://github.com/fluent/fluent-package-builder.
Experimental Ubuntu jammy support is in progress: https://github.com/fluent/fluent-package-builder/pull/381

**Comment by pyama86** [comment]
Thanks for your quick response!
