### ISSUE TITLE
Td-agent not able to install in customize path instead of default path

### ISSUE THREAD

**Issue by Priyankanavalagund** [treasure-data/omnibus-td-agent#303]
I am trying to install td-agent in centos with below cmd
curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent4.sh | sh

But its installing default location /opt/td-agent/bin but i need to install customize path like this /DG/activeRelease/IDAP/

while installing td-agent by default ruby also installed in default location. so ruby is pointing to default path. i need help how we can install td-agent in customize path.

Please help me as soon as possible. Thank you so much for your help

**Comment by ashie** [comment]
For td-agent v4 or later, please file issues to https://github.com/fluent/fluent-package-builder/issues instead of here.

There is no way to change install path of official td-agent package.
If you really want to this, you need to modify the build system to create your own package.

**Comment by Priyankanavalagund** [comment]
> For td-agent v4 or later, please file issues to https://github.com/fluent/fluent-package-builder/issues instead of here.
> 
> There is no way to change install path of official td-agent package. If you really want to this, you need to modify the build system to create your own package.

Thank you so much @ashie. how to build system to create own packages if you have any commend or guide it will be great help for us.
