### ISSUE TITLE
liblzma 5.0.5/5.1.2 are no longer available

### ISSUE THREAD

**Issue by mr-salty** [treasure-data/omnibus-td-agent#57]
see https://github.com/chef/omnibus-software/issues/504

This is an additional issue for td-agent since we force 5.1.2alpha on centos7.  So, I think we have two options:

- Change the default version to 5.0.8 and change the centos7 version to 5.2.2.
- Just change to 5.2.2 for all platforms

Let me know what you think and I'll send a PR... We can also wait to see what the chef/omnibus folks think, if they decide to go with 5.2.2 then we can just remove the customizations here.

**Comment by repeatedly** [comment]
> Just change to 5.2.2 for all platforms

Are there no problem on platforms? If so, using same versions are easy to maintain.

**Comment by mr-salty** [comment]
no issues AFAIK.  Let me try to get it fixed upstream, in which case we can just remove our local version.
