### ISSUE TITLE
Cannot use @ in field name in regex

### ISSUE THREAD

**Issue by oazabir** [treasure-data/omnibus-td-agent#60]
For elasticsearch, I need to use the timestamp name as @timestamp. However, such regex is invalid:

(?<\@timestamp>[^ ]*)

invalid char in group name <\@timestamp>: /(?<\@timestamp>[^ ]*)

**Comment by repeatedly** [comment]
This is current Ruby's regexp limitation.
You need to use `record_transformer` filter or implement simple parser to convert `time` to `@timestamp`.
I will submit an issue to Ruby for allowing `@` prefix capture name.

**Comment by repeatedly** [comment]
I checked elasticsearch plugin and it has `time_key` configuration > https://github.com/uken/fluent-plugin-elasticsearch#time_key
This resolves your problem without `@` prefix field name.

**Comment by repeatedly** [comment]
Submit feature request to Ruby: https://bugs.ruby-lang.org/issues/11949

**Comment by oazabir** [comment]
Many thanks for the help.

**Comment by repeatedly** [comment]
'@' issue is fixed in the Ruby trunk: https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?revision=53610&view=revision
