### ISSUE TITLE
Missing versions in apt repositories

### ISSUE THREAD

**Issue by trekdemo** [treasure-data/omnibus-td-agent#66]
Dear All,

I wanted to install an older version of td-agent on a Debian like system (to keep consistent boxes), but I wasn't able because in the apt repositories of treasure data the only available version is always the latest. (This is not the case in the yum repo.)

``` shell
vagrant@vagrant-ubuntu-trusty-64:~$ sudo apt-get install td-agent=2.2.1-0*
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '2.2.1-0*' for 'td-agent' was not found
```

Can you check if it's possible to list all available versions in the apt repo as well?

Thank you!

cc @edsiper

**Comment by repeatedly** [comment]
This is current reprepro limitation.
apt repository has older versions but reprepro publishes only latest package.
We are considering replace reprepro with other package management tool like mini_dinstall or something.

**Comment by trekdemo** [comment]
Thanks, that's good news.

**Comment by repeatedly** [comment]
aptly can handle multiple versions.
We will switch the reprepro based repository to aptly.

**Comment by jsmickey** [comment]
After the upgrade yesterday, we are not able to install 2.3.1-0 from the apt repo.  We are configuring the repo and installing td-agent with Chef via:
https://github.com/treasure-data/chef-td-agent/blob/master/recipes/default.rb#L44

Is there a way to get older version from the repo other than https direct link?

**Comment by repeatedly** [comment]
@jsmickey Currently, no way. I will have a plan to replace repo with aplyt for providing older versions.

**Comment by repeatedly** [comment]
After LinuxCon, I will try to replace repository with aptly.

**Comment by repeatedly** [comment]
I'm now working on it.
Maybe, I will replace current repository with aptly in this month with older packages.

**Comment by repeatedly** [comment]
We have released td-agent 3 and td-agent 3's deb repository is built on aptly.
aptly supports multiple versions in one repository so you can specify version since td-agent 3.
We use reprepro for td-agent 2 repository so single version limitation still exist.

I closed this issue.
