### ISSUE TITLE
Gem file compatibility issues are causing builds to fail

### ISSUE THREAD

**Issue by IainColledge** [treasure-data/omnibus-td-agent#68]
With a fresh rvm install with ruby 2.2.1 when running bundle install --binstubs the following errors come up. 

Happens with release omnibus-td-agent v2.2.1 through to current and ruby-1.9.2-p330 through to 2.2.1, although the incompatible gems may change slightly.

Changed versions of td-agent with git checkout i.e

```
git checkout v2.2.1
bundle install --binstubs
```

```
Bundler could not find compatible versions for gem "celluloid":
   In Gemfile:
     berkshelf (~> 3.0) was resolved to 3.0.0, which depends on
       celluloid (~> 0.16.0.pre)
 
     berkshelf (~> 3.0) was resolved to 3.0.0, which depends on
       celluloid-io (~> 0.16.0.pre) was resolved to 0.16.5.pre0, which depends on
         celluloid (>= 0.17.0.pre12)
 Bundler could not find compatible versions for gem "multipart-post":
   In Gemfile:
     berkshelf (~> 3.0) was resolved to 3.0.0, which depends on
       ridley (~> 3.0) was resolved to 3.0.0, which depends on
         faraday (~> 0.9.0) was resolved to 0.9.2, which depends on
           multipart-post (< 3, >= 1.2)
 
     omnibus was resolved to 5.0.0, which depends on
       pedump (~> 0.5) was resolved to 0.5.0, which depends on
         multipart-post (~> 1.1.4)
```

**Comment by repeatedly** [comment]
Could you check this patch? > https://github.com/treasure-data/omnibus-td-agent/pull/67

**Comment by IainColledge** [comment]
v2.2.0 doesn't have this problem.

Yes would love to, sorry to ask a noob question but how do I do that?

**Comment by repeatedly** [comment]
Download patch and `git apply` it: https://patch-diff.githubusercontent.com/raw/treasure-data/omnibus-td-agent/pull/67.patch

**Comment by IainColledge** [comment]
Thank you, will do and report back

**Comment by IainColledge** [comment]
Patch does the trick, thank you.

**Comment by IainColledge** [comment]
The patch stops the dependancy errors.

**Comment by repeatedly** [comment]
Merged above patch.
