### ISSUE TITLE
Agent install scripts points to Trusty repo over plain HTTP

### ISSUE THREAD

**Issue by therc** [treasure-data/omnibus-td-agent#71]
Hello!
If you open `https://td-toolbelt.herokuapp.com/sh/install-ubuntu-trusty-td-agent2.sh` you'll see that it runs curl against an HTTPS URL, but then sets up the APT repo with a plain HTTP URL. Is this intended? I guess the key is protected, so any man-in-the-middle attack could, at worse, only cause denial of service, but these days TLS overhead should be negligible.
Thanks in advance.

**Comment by repeatedly** [comment]
We follow the official APT setting.
APT repos of `/etc/apt/source.list` are also HTTP URL.
Does these official repos also have the problem?

**Comment by repeatedly** [comment]
No response
