### ISSUE TITLE
Support for Amazon Linux 2016.03

### ISSUE THREAD

**Issue by tilfin** [treasure-data/omnibus-td-agent#75]
Amazon Linux 2013.03 has been released.
https://aws.amazon.com/amazon-linux-ami/2016.03-release-notes/

Please apply new vesion to `install-redhat-td-agent2.sh` script.
The script currently failed because `http://packages.treasuredata.com/2/redhat/2016.03/x86_64/repodata/repomd.xml` is not found.

**Comment by repeatedly** [comment]
The problem is not the script.
We didn't build the td-agent for amazon linux 2016.03 yet.

**Comment by tilfin** [comment]
Oh, that's right. Please take care of this issue.

**Comment by repeatedly** [comment]
I will build it.
Please wait...

**Comment by repeatedly** [comment]
I just uploaded rpm for 20.16.03.
Could you retry installation on Amazon Linux 2016.03?

**Comment by tilfin** [comment]
I could successfully install it on Amazon Linux 2016.03.
Thank you very much for your support!
