### ISSUE TITLE
compression during out_forward

### ISSUE THREAD

**Issue by Manikantan22** [treasure-data/omnibus-td-agent#76]
I am looking for a option to compress (snappy/gzip) a message during out_forward. Could someone help me?

Do we still have "compress true" for out_forward plugin (https://github.com/fluent/fluentd/issues/504)?

I am using td-agent2 and tried to use compress true but getting below error in logs.

[warn]: parameter 'compress' in is not used.

**Comment by repeatedly** [comment]
replied on fluentd PR 637
