### ISSUE TITLE
unable to decompress the message which is read from kafka

### ISSUE THREAD

**Issue by Manikantan22** [treasure-data/omnibus-td-agent#77]
I am doing a snappy compression in Java and sending the data to Kafka through fluentd but I am unable to read the original message from kafka since fluentd is sending the data as a string not as a byte[]. Any suggestion on this? what should be the configuration I should use in this case?

here is the fluentd configuration.

```aconf
<match *.**>
  @type               kafka_buffered
  brokers             <broker1_host>:<broker1_port>,<broker2_host>:<broker2_port>
  default_topic      topic
  flush_interval      10s
  buffer_type        file
  buffer_path /app/logs
  buffer_chunk_limit 64m
  buffer_queue_limit 700
  disable_retry_limit true
  output_data_type json
  output_include_tag true
  output_include_time true
  max_send_retries 3
  required_acks 1
  ack_timeout_ms 1500
  compression_codec none
</match>
```

**Comment by repeatedly** [comment]
> fluentd is sending the data as a string not as a byte[]

Is this a fluentd issue? Why your consumer can't deal with these message?

**Comment by Manikantan22** [comment]
Basically, If I compress the data externally and send it from fluentd client,I couldn't compress the entire message. Meaning, We are keeping messages in hash map and sending, so key should be a String and value is a compressed byte[]. So consumer is not able to deal with the partial compressed message. If this is not the right way, please suggest me a good way of dealing with the compression and decompression.


Client code:
-------------

FluentLogger LOG = FluentLogger.getLogger("pattern","host", port);
String message="The federation of text compression is dominantly made up of lossless compression algorithms. (excluding the edge cases for text-based, floating point data you may have laying around). These are typical compression algorithms that allow the source stream to be recovered directly without any loss of precision or information.";

 byte[] compressed=null;
	try {
	     compressed = Snappy.compress(message.getBytes("UTF-8"));
	} catch (IOException e) {
	   e.printStackTrace();
	}
Map<String, Object> data = new HashMap<String, Object>();
data.put("log",compressed);
LOG.log("dartLog", data);

Result (when fetching from kafka): 				Partial compression
-----------------------------------------

Here log is a key that we used for storing the data in hash map which is not compressed. so my consumer is not able to decompressed it.

regular String + compressed message

{"log":"?\u0002xThe federation of text compress\u0001\u0014Pis dominantly made up\u0001*\u001Clossless2.\u0000?algorithms. (excluding the edge cases for\u0005i0-based, float\u0001(hpoint data you may have lay\u0001\u001Fdaround). These are typicalZ?\u0000( that allow\u0005??source stream to be recovered direc\u0001?(without any\u0005?\u0001?\u0010preci%\u00128or information."}

**Comment by repeatedly** [comment]
I tested similar routine in ruby and it worked.

- sender

```rb
require 'fluent-logger'
require 'snappy'

logger = Fluent::Logger::FluentLogger.new(nil, :host=>'localhost', :port=>24230)
message = 'fooo!'
logger.post('kafka.test', {'log' => Snappy.deflate(message)})
logger.close
```

- fluentd.conf

```aconf
<source>
  @type forward
  port 24230
</source>

<match kafka.**>
  @type kafka_buffered
  default_topic snappy_test
  flush_interval 1s
  buffer_type memory
  output_data_type json
  output_include_time
  output_include_tag
  required_acks 1
  compression_codec none
</match>
```

- consumer

```aconf
require 'poseidon'
require 'snappy'
require 'json'

consumer = Poseidon::PartitionConsumer.new(
  "my_test_consumer", "localhost", 9092, "snappy_test", 0, :earliest_offset)

loop do
  messages = consumer.fetch
  messages.each do |m|
    puts Snappy.inflate(JSON.parse(m.value)['log'])
  end
end
```

Output result is `fooo!`.

I still can't judge this is a fluentd / plugin issue or not.
