### ISSUE TITLE
LSB dependency not working for CentOS

### ISSUE THREAD

**Issue by cbroglie** [treasure-data/omnibus-td-agent#78]
#70 added dependencies on the LSB functions for init.d scripts, but the logic does not work for CentOS platforms. In particular:

```ruby
case ohai["platform"]
when "linux"
  case ohai["platform_family"]
  when "debian"
    dependency "lsb-base"
  when "rhel"
    dependency "initscripts"
    dependency "redhat-lsb"
  end
end
```

For CentOS, the value of `ohai["platform"]` is `centos`, so no dependencies are added. This means the `redhat-lsb-core` package needs to be manually installed for the generated td-agent init.d scripts to function (they rely on `/lib/lsb/init-functions`, which is provided by `redhat-lsb-core`).

Separately, I don't know where the `redhat-lsb` and `initscripts` software are defined. They are not in this code base nor do I see them in the [omnibus-software](https://github.com/chef/omnibus-software/tree/master/config/software) repo. If I fix the logic in the td-agent.rb software to include the dependencies for CentOS, I get the following error:

```
I could not find a software named `initscripts' in any of the software locations:"

    /home/vagrant/omnibus-td-agent/config/software
    /home/vagrant/.bundler/ruby/2.1.0/bundler/gems/omnibus-software-46b5677a209d/config/software
```

**Comment by repeatedly** [comment]
Thanks for the reporting

@yyuu Could you check this?
Maybe, using `runtime_dependency` instead of `dependency` is needed.

**Comment by repeatedly** [comment]
@cbroglie If you have a time, could you try `runtime_dependency` instead of `dependency` for these lines?

**Comment by yyuu** [comment]
Ah, sorry. I was overlooked this 😭
