### ISSUE TITLE
td-agent 3.0

### ISSUE THREAD

**Issue by repeatedly** [treasure-data/omnibus-td-agent#80]
Update components:
- ruby 2.4
- fluentd v0.14
- other core libraries

New plugins:
- fluent-plugin-elasticsearch (after merge optimized patch)

New support OS:
- Windows

Drop OS:
- CentOS 5
- Ubuntu 10.04

Drop plugins:
- fluent-plugin-scribe
- fluent-plugin-mongo

**Comment by repeatedly** [comment]
We have a plan to release td-agent 3 experimental package.
Maybe, stable release is the end of 2016 or 2017 earlier, so we have a chance to use ruby 2.4 instead of ruby 2.3.

**Comment by repeatedly** [comment]
I tried `in_tail -> record_transformer -> out_forward` case with ruby 2.4.0-preview2.
CPU usage of ruby 2.4.0-preview2 is lower than ruby 2.3.1.
So I decided to use ruby 2.4 series for td-agent 3.
td-agent 3 experimental uses ruby 2.4.0-preview2.

**Comment by Raboo** [comment]
Hi, is td-agent 3 experimental package in a repository somewhere?
I would like to test it out to test the millisecond/nanosecond support introduced in fluentd 0.14.

**Comment by repeatedly** [comment]
We need to release new td CLI gem for msgpack v1.0.0 support.
This is the blocker. After released, we will release td-agent 3 experimental.
