### ISSUE TITLE
JSON parser for Elasticsearch 2.x

### ISSUE THREAD

**Issue by jasonhr13** [treasure-data/omnibus-td-agent#85]
We are running into an issue where Elasticsearch 2.x now does not allow field names to use dots i.e (params.id). We use the json parser within td-agent to parse our json logs and it adds dots to the output when outputting nested items inside an object.

{ data: { attr1: 1, attr2: 2 } }
is outputted as
{ data.attr1: 1, data.attr2: 2 }

Could you assist in pointing me in the right direction to solve this. Possibly taking the current json parser built into td-agent and reworking it to add underscores instead of dots?

Where is the code for that default json parser in this repo?

**Comment by repeatedly** [comment]
> We use the json parser within td-agent to parse our json logs and it adds dots to the output when outputting nested items inside an object.

td-agent doesn't bundle such parser plugins. If you want to do it, writing own parser or filter is better:

http://docs.fluentd.org/articles/plugin-development

Or using existing filter like flatten-hash:

https://github.com/kazegusuri/fluent-plugin-flatten-hash
