### ISSUE TITLE
Issue Installing fluentd

### ISSUE THREAD

**Issue by rodaan** [treasure-data/omnibus-td-agent#95]
Hi,

I'm trying to install fluentd on a CentOS box and I'm getting this error:

curl: (7) Failed connect to packages.treasuredata.com:443; Connection timed out
error: https://packages.treasuredata.com/GPG-KEY-td-agent: import read failed(2).
Loaded plugins: fastestmirror, langpacks
base                                                     | 3.6 kB     00:00     
http://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/5/repodata/repomd.xml: [Errno 12] Timeout on http://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/5/repodata/repomd.xml: (28, 'Connection timed out after 30179 milliseconds')

This happens when I run this command:
curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh | sh

Can someone help me with this?

Thanks,

Rodaan

**Comment by repeatedly** [comment]
I tested on my CentOS 6 and there is no problem.

> Can someone help me with this?

It seems your environment dependent issue, so we can't reply correct answer.
Please check OS setting, network, firewall or something.

**Comment by repeatedly** [comment]
Closed. If the problem is td-agent repository side, reopen this issue.

**Comment by OutingDay** [comment]
I am alsi facing same issue whats the resolution ?
