### ISSUE TITLE
How to uninstall td-agent?

### ISSUE THREAD

**Issue by edwin-lai** [treasure-data/omnibus-td-agent#99]
This is not documented anywhere.

**Comment by yyuu** [comment]
Obviously it's depending on the platform you are (were?) using to run `td-agent`.

**Comment by edwin-lai** [comment]
Platform is Mac OS X. I installed using the dmg provided on the website.

**Comment by repeatedly** [comment]
Removing these files and directories:

- /Library/LaunchDaemons/td-agent.plist
- /etc/td-agent
- /opt/td-agent

**Comment by repeatedly** [comment]
I just added this point to docs: http://docs.fluentd.org/articles/install-by-dmg#uninstall-td-agent

**Comment by edwin-lai** [comment]
Thanks!

**Comment by kk-fan** [comment]
> 删除这些文件和目录：
> 
> * /图书馆/LaunchDaemons/td-agent.plist
> * / etc / td-agent
> * / opt / td-agent
> * / var / log / td-agent

How to uninstall under Debian?
